name: Swift
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Lint with SwiftFormat
      run: /usr/bin/xcrun swift-format lint -r -p .
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
